### ISSUE TITLE
Testing Auth Route(Login, Register, Send OTP) API

### ISSUE THREAD

**Issue by manojtsx** [manojtsx/GyanShristi-CMS#42]
### Discussed in https://github.com/manojtsx/GyanShristi-CMS/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **manojtsx** July 27, 2024</sup>
Here is a list of route with tasks:

1. `POST /api/auth/register` - Registers the user

-  If all the details are valid and verified, the shows "Registered Successfully" (200)
-  If the OTP is not correct, it shows "Invalid OTP" (400)
-  If registered with an existing username, it shows "Username already exists." (400)
-  If try to register without requesting OTP, it shows "Please request OTP first" (400)
-  If any field is missing, then it shows "Missing field Error" (400)
-  Email, Username, Password, Name must be at least 3 characters long, password be 8 characters long and phone number be 10 characters long or else throws error (400)
- Email, Username, Password, Name, password, phone number must be at most 255 characters long, or else throws error (400)

2. `POST /api/auth/login` - Registers the user

-  Shows "Logged in Successfully" with a token and login details. (200)
-  Shows "Credentials error" or "Password do not match" on incorrect username or password (400)
-  Shows "Credentials error" on non-existent username (400)
-  If any field is missing, then it shows "Missing field Error" (400)
-  username and password must be at least 3 characters long or else throws error (400)
- username and password must be at mot 255 characters long or else throws error (400)

3. `POST /api/auth/sendOTP` - Send OTP to the email provided

- If OTP is sent, the it shows "You have received OTP in your email" (200)
-  or else show 'Error sending OTP' if any error occurs like email usage limitation.

Note: Don't forget to look at the changes in the database after calling the API everytime.
</div>

**Comment by seezan25** [comment]
Sent OTP Through: http://localhost:3001/api/auth/sendOTP by POST method,
Body:
{
    "email" : "shresthanewar678@gmail.com"
}

Tried to register from http://localhost:3001/api/auth/register by POST method.
Body:
{
  "name": "John Doe",
  "username": "johndoe123",
  "password": "SecureP@ssw0rd!",
  "email": "shresthanewar678@gmail.com",
  "address": "123 Main Street, Apt 4B, Springfield, USA",
  "phone_number": "+1234567890",
  "otp": "342258"
}
Note: The OTP is sent to the email address successfully.

**Comment by seezan25** [comment]
For (If registered with an existing username, it shows "Username already exists." (400)), we need to solve the Invalid OTP problem

**Comment by seezan25** [comment]
Tried to register through:http://localhost:3001/api/auth/register,
Body: 
{
  "name": "Jghghhggh",
  "username": "johndoe1",
  "password": "SecureP@ssw0rd!",
  "email": "shresthanewar67@gmail.com",
  "address": "",
  "phone_number": "+1234567890",
  "otp": "227973"
}
Problem: Got "Please request OTP first" error message while registering the new user without requesting OTP while address field is left empty

**Comment by seezan25** [comment]
Tried to register new user through:http://localhost:3001/api/auth/register,
Body:
{
"name": "Jghghhggh",
"username": "johndoe1",
"password": "",
"email": "[shresthanewar67@gmail.com](mailto:shresthanewar67@gmail.com)",
"address": "123 Main Street, Apt 4B, Springfield, USA",
"phone_number": "+1234567890",
"otp": "227973"
}
Problem: Got "Password must be at least 3 characters long" error but it have to show "Password must be 8 character long"

**Comment by seezan25** [comment]
Tried to register new user through:http://localhost:3001/api/auth/register,
Body:
{
"name": "Jghghhggh",
"username": "johndoe1",
"password": "SecureP@ssw0rd!",
"email": "[shresthanewar67@gmail.com](mailto:shresthanewar67@gmail.com)",
"address": "123 Main Street, Apt 4B, Springfield, USA",
"phone_number": "1234",
"otp": "227973"
}
Problem: Got "Phone number must be at least 3 characters long" error but it have to show "Phone number must be 10 character long"

**Comment by seezan25** [comment]
Tried to register new user through:http://localhost:3001/api/auth/register,
Body:
{
"name": "Jghghhggh",
"username": "johndoe1",
"password": "SecureP@ssw0rd!",
"email": "[shresthanewar67@gmail.com](mailto:shresthanewar67@gmail.com)",
"address": "123 Main Street, Apt 4B, Springfield, USA Alexander Benedict Christopher Douglas Edward Fitzwilliam Gregory Harrison Isaiah Jonathan Kingsley Laurence Montgomery Nathaniel Oliver Percival Quentin Randolph Sebastian Theodore Ulysses Victor William Xavier York Zachary Athelstan Basil Clarence David Everett Frederick George Hiram Ignatius James Kenneth Leonard Maximilian Nicholas Octavius Phineas Quentin Reginald Samson Thaddeus Ulrich Valentine Walter Xander Yule Zacharias",
"phone_number": "1234",
"otp": "227973"
}
Problem: Got "Please request OTP first" error message while registering the new user without requesting OTP while address field is more than 255 characters

**Comment by seezan25** [comment]
Tried to register new user through:http://localhost:3001/api/auth/register,
Body:
{
  "name": "John Doe",
  "username": "johndoe123",
  "password": "SecureP@ssw0rd!",
  "email": "johndoe@example.com",
  "address": "123 Main Street, Apt 4B, Springfield, USA",
  "phone_number": "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890975645453333556787890909",
  "otp": "123456"
}

Problem: Got "Please request OTP first" error message while registering the new user without requesting OTP while Phone_number field is more than 255 characters long, while it have to show "Phone number must be 14 character long"

**Comment by seezan25** [comment]
Tried to login through : http://localhost:3001/api/auth/login by POST method
body:
{
    "username": "     johndoe123",
    "password": "password"
}

Problem: Got "credential error" error while it have to cut any whitespace in the beginning of the first character

**Comment by seezan25** [comment]
Tried to login through : http://localhost:3001/api/auth/login by POST method
body:
{
"username": " johndoe123",
"password": "      password"
}

Problem: Got "credential error" error while it have to cut any whitespace in the beginning of the first character in the password field

**Comment by seezan25** [comment]
Note: Trim every whitespaces before and after the characters in every field while registering

**Comment by manojtsx** [comment]
> Tried to register new user through:http://localhost:3001/api/auth/register, Body: { "name": "Jghghhggh", "username": "johndoe1", "password": "", "email": "[shresthanewar67@gmail.com](mailto:shresthanewar67@gmail.com)", "address": "123 Main Street, Apt 4B, Springfield, USA", "phone_number": "+1234567890", "otp": "227973" } Problem: Got "Password must be at least 3 characters long" error but it have to show "Password must be 8 character long"

Solved

**Comment by manojtsx** [comment]
> Tried to register new user through:http://localhost:3001/api/auth/register, Body: { "name": "John Doe", "username": "johndoe123", "password": "SecureP@ssw0rd!", "email": "[johndoe@example.com](mailto:johndoe@example.com)", "address": "123 Main Street, Apt 4B, Springfield, USA", "phone_number": "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890975645453333556787890909", "otp": "123456" }
> 
> Problem: Got "Please request OTP first" error message while registering the new user without requesting OTP while Phone_number field is more than 255 characters long, while it have to show "Phone number must be at most 15 character long"

Solved

**Comment by seezan25** [comment]
This issue is completed
